const canvas = document.querySelector('#codex');
const ctx = canvas.getContext('2d');
const poem = document.querySelector('#poem');
const seed = document.querySelector('#seed');
const translation = document.querySelector('#translation');
const grammar = document.querySelector('#grammar');
let rand, glyphs;

function hash(text) { let h=2166136261; for (const c of text) { h^=c.charCodeAt(0); h=Math.imul(h,16777619); } return h>>>0; }
function rng(value) { let a=value>>>0; return () => { a|=0;a=a+0x6D2B79F5|0;let t=Math.imul(a^a>>>15,1|a);t=t+Math.imul(t^t>>>7,61|t)^t;return ((t^t>>>14)>>>0)/4294967296; }; }
function setup() { rand=rng(hash(seed.value || 'unnamed')); glyphs={}; 'abcdefghijklmnopqrstuvwxyz'.split('').forEach(c=>glyphs[c]=Array.from({length:2+(rand()*3|0)},()=>[rand(),rand(),rand(),rand(),rand(),rand()])); }
function fakeText(str) { const rune=['⟆','ʚ','⋔','ꝏ','ᚫ','⸸','ꜥ','⨳','᛫','❦']; let i=0; return str.toLowerCase().replace(/[a-z]/g,()=>rune[(hash(seed.value+i++)+i*7)%rune.length]).replace(/\s+/g,' '); }
function lineWrap(text,max) { const words=text.split(/\s+/),lines=[];let line=[];for(const word of words){if((line.join(' ').length+word.length)>max){lines.push(line.join(' '));line=[];}line.push(word)}if(line.length)lines.push(line.join(' '));return lines; }
function glyph(c,x,y,s) { const paths=glyphs[c]; if(!paths)return 12*s; ctx.save();ctx.strokeStyle='#3d354f';ctx.fillStyle='#3d354f';ctx.lineWidth=2.2*s;ctx.lineCap='round';ctx.lineJoin='round'; for(const p of paths){ctx.beginPath();ctx.moveTo(x+p[0]*22*s,y-p[1]*34*s);ctx.quadraticCurveTo(x+p[2]*23*s,y-p[3]*35*s,x+p[4]*25*s,y-p[5]*34*s);ctx.stroke();} const r=rng(hash(c+seed.value));if(r()>.42){ctx.beginPath();ctx.arc(x+(r()*18+2)*s,y-(r()*25+17)*s,2.1*s,0,Math.PI*2);ctx.fill()}ctx.restore();return 29*s; }
function petal(x,y,r,rot) { ctx.save();ctx.translate(x,y);ctx.rotate(rot);ctx.beginPath();ctx.moveTo(0,0);ctx.bezierCurveTo(-r*.38,-r*.18,-r*.35,-r*.92,0,-r);ctx.bezierCurveTo(r*.35,-r*.92,r*.38,-r*.18,0,0);ctx.fill();ctx.stroke();ctx.restore(); }
function flower(x,y,r) { ctx.save();ctx.fillStyle='#d887a4';ctx.strokeStyle='#3d354f';ctx.lineWidth=1.4;for(let i=0;i<5;i++)petal(x,y,r,i*Math.PI*2/5);ctx.fillStyle='#d6ad52';ctx.beginPath();ctx.arc(x,y,r*.25,0,7);ctx.fill();ctx.restore(); }
function tower(x,y,s,flip=1) { ctx.save();ctx.translate(x,y);ctx.scale(flip,1);ctx.strokeStyle='#3d354f';ctx.fillStyle='#9cae9a';ctx.lineWidth=3*s;ctx.fillRect(-34*s,0,68*s,250*s);ctx.strokeRect(-34*s,0,68*s,250*s);ctx.beginPath();ctx.moveTo(-45*s,0);ctx.lineTo(0,-74*s);ctx.lineTo(45*s,0);ctx.closePath();ctx.fill();ctx.stroke();ctx.fillStyle='#f5c4cf';ctx.fillRect(-19*s,42*s,38*s,154*s);ctx.strokeRect(-19*s,42*s,38*s,154*s);for(let yy=58*s;yy<184*s;yy+=35*s){ctx.beginPath();ctx.arc(0,yy,10*s,0,7);ctx.stroke();}ctx.restore(); }
function vine(x1,y1,x2,y2,steps=5) { ctx.save();ctx.strokeStyle='#4e5d55';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(x1,y1);ctx.bezierCurveTo(x1+(x2-x1)*.15,y1-42,x1+(x2-x1)*.72,y2-36,x2,y2);ctx.stroke();for(let i=1;i<steps;i++){let t=i/steps,x=x1+(x2-x1)*t,y=y1+(y2-y1)*t-35*Math.sin(t*Math.PI);ctx.fillStyle='#bf698b';flower(x,y,10+(i%2)*2);}ctx.restore(); }
function paper() { const w=canvas.width,h=canvas.height; ctx.fillStyle='#f5d6d0';ctx.fillRect(0,0,w,h);const noise=rng(hash(seed.value+'paper'));for(let i=0;i<8800;i++){ctx.fillStyle=`rgba(114,57,81,${.012+noise()*.035})`;ctx.fillRect(noise()*w,noise()*h,1+noise()*3,1+noise()*3)}ctx.strokeStyle='#3d354f';ctx.lineWidth=4;ctx.strokeRect(26,26,w-52,h-52);ctx.strokeStyle='#c37d96';ctx.lineWidth=2;ctx.strokeRect(43,43,w-86,h-86); }
function draw() { setup(); const w=canvas.width,h=canvas.height,s=w/1200; paper();
  // Original Gothic garden frame: towers, medallion, vines, and petals.
  tower(105*s,190*s,s);tower(1095*s,190*s,s,-1);ctx.strokeStyle='#3d354f';ctx.fillStyle='#9cae9a';ctx.lineWidth=4*s;ctx.beginPath();ctx.moveTo(140*s,200*s);ctx.quadraticCurveTo(600*s,58*s,1060*s,200*s);ctx.lineTo(1040*s,228*s);ctx.quadraticCurveTo(600*s,112*s,160*s,228*s);ctx.closePath();ctx.fill();ctx.stroke();
  ctx.fillStyle='#e5a2b7';ctx.beginPath();ctx.arc(600*s,125*s,47*s,0,7);ctx.fill();ctx.stroke();ctx.fillStyle='#3d354f';ctx.font=`italic ${26*s}px Libre Baskerville`;ctx.textAlign='center';ctx.fillText('✦',600*s,134*s);ctx.textAlign='left';
  vine(150*s,210*s,350*s,315*s);vine(1050*s,210*s,850*s,315*s);flower(237*s,255*s,14*s);flower(964*s,255*s,14*s);
  ctx.fillStyle='#7b3f58';ctx.font=`bold ${27*s}px Libre Baskerville`;ctx.textAlign='center';ctx.fillText(`THE ${hash(seed.value).toString(36).toUpperCase()} CHAPTER`,600*s,265*s);ctx.textAlign='left';
  const lines=lineWrap(poem.value,33);let y=390*s; lines.slice(0,13).forEach((line,li)=>{let x=220*s; for(let i=0;i<line.length;i++){const c=line[i].toLowerCase();if(/[a-z]/.test(c)){if(li===0&&i===0){ctx.fillStyle='#c97b9a';ctx.strokeStyle='#3d354f';ctx.lineWidth=2*s;ctx.fillRect(x-11*s,y-50*s,45*s,58*s);ctx.strokeRect(x-11*s,y-50*s,45*s,58*s);}x+=glyph(c,x,y,li===0&&i===0?1.35*s:s)}else if(c===' ')x+=14*s;else{x+=13*s;ctx.fillStyle='#8b4363';ctx.beginPath();ctx.arc(x,y-10*s,3*s,0,7);ctx.fill();}}y+=60*s;});
  ctx.strokeStyle='#3d354f';ctx.fillStyle='#9cae9a';ctx.lineWidth=2*s;ctx.fillRect(115*s,h-190*s,970*s,32*s);ctx.strokeRect(115*s,h-190*s,970*s,32*s);for(let x=160*s;x<1040*s;x+=76*s){ctx.beginPath();ctx.arc(x,h-174*s,19*s,Math.PI,0);ctx.stroke();flower(x,h-177*s,8*s);}ctx.fillStyle='#4d4657';ctx.font=`italic ${14*s}px Libre Baskerville`;ctx.fillText('Breath reverses the next word · Sacred pairs bind into one hand · No glossary survives.',180*s,h-95*s);
 translation.textContent=fakeText(poem.value); grammar.textContent=`Grammar of the ${hash(seed.value).toString(36).toUpperCase()} hand: verbs take a hooked ascender; pauses become votive marks; th, sh, and ch are sacred ligatures.`;
}
document.querySelector('#transmute').addEventListener('click',draw); document.querySelector('#new-seed').addEventListener('click',()=>{seed.value=Math.random().toString(36).slice(2,10);draw()});document.querySelector('#download').addEventListener('click',()=>{const a=document.createElement('a');a.download='asemic-codex.png';a.href=canvas.toDataURL('image/png');a.click();});
draw();
